server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ratingmicroservice
    username: postgres
    password: Passw0rd.

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: RATING-SERVICE
  config:
    import: configserver:http://localhost:8086


#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    prefer-ip-address: true

okta:
  oauth2:
    issuer: https://dev-21286665.okta.com/oauth2/default
    audience: api://default
