server:
  port: 8086

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/Mintu-Kumar/microservice-common-configuration
          clone-on-start: true