spring:
  application:
    name: USER-SERVICE

  config:
    import: configserver:http://localhost:8086

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-21286665.okta.com/oauth2/default
      client:
        registration:
          my-internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaabpt6xvws7ZBso5d7
            client-secret: gqIqll_Z4Vuq_rvXNrMT9GcwB26BlWudyXQdwoPZ

        provider:
          okta:
            issuer-uri: https://dev-21286665.okta.com/oauth2/default


#eureka:
 # instance:
  #  hostname: localhost
  #client:
   # register-with-eureka: false
    #fetch-registry: false

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitebreaker:
    instances:
      ratingHotelBreaker:
        registerHealthBreaker: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
  retry:
    instances:
      serviceHotelRetry:
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      userRateLimiter:
        limit-refresh-period: 4s
        limit-for-period: 2
        timeout-duration: 0s

okta:
  oauth2:
    issuer: https://dev-21286665.okta.com/oauth2/default
    audience: api://default




